# Generated by Django 4.2.1 on 2025-01-08 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('women', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='women',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='women',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
