# Generated by Django 4.2.1 on 2025-01-08 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('women', '0002_women_updated_at_alter_women_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='women',
            name='is_published',
            field=models.BooleanField(default=True),
        ),
    ]
